#!/usr/bin/env bash

if ! command -v node &> /dev/null; then
    echo "Error: node.js is not installed"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo "Error: npm is not installed"
    exit 1
fi

npm start --silent -- "$@"
